import { GameItem, GameKey } from "@/types/database.types";

export const MOCK_GAMES: GameItem[] = [
  // 1. Кейіпкерді тап
  {
    id: "game-1",
    key: "find_character",
    title: "Кейіпкерді тап",
    subtitle: "Сөздер мен белгілерден кейіпкерді таны",
    category: "Кейіпкерлер әлемі",
    description: "Ертегілердегі кейіпкерлердің сипаттамасы мен сөздеріне қарап, олардың кім екенін дұрыс тап!",
    book_id: "book-1",
    book_title: "Қазақ халық ертегілері",
    emoji: "🎮",
    color: "sky",
    bg_gradient: "from-sky-500 to-blue-600",
    points_reward: 30,
    coins_reward: 40,
    badge_reward: "Тапқыр оқырман 🎯",
    questions_count: 3,
    difficulty: "жеңіл",
    questions: [
      {
        id: "g1-q1",
        game_id: "game-1",
        question_text: "Үйін сыпырып жүріп бір мейіз тауып алған кейіпкер кім?",
        clue_kk: "Ол мысығын шақырып, келмеген соң мейізді өзі жеп қойды.",
        book_title: "Мақта қыз бен мысық",
        mechanic: "character_pick",
        points: 10,
        options: [
          { id: "g1-o1", text: "Мақта қыз 👧", emoji: "👧", is_correct: true, explanation_kk: "Дұрыс! Мақта қыз мейіз тауып алды." },
          { id: "g1-o2", text: "Мыстан кемпір 🧙‍♀️", emoji: "🧙‍♀️", is_correct: false },
          { id: "g1-o3", text: "Қарлығаш 🕊️", emoji: "🕊️", is_correct: false },
          { id: "g1-o4", text: "Тауық 🐔", emoji: "🐔", is_correct: false },
        ],
      },
      {
        id: "g1-q2",
        game_id: "game-1",
        question_text: "Алтын сақасы алысқа домалап кеткенде, тапқырлығымен мыстаннан құтылған батыр бала кім?",
        clue_kk: "Ол жүйрік тұлпарына мініп еліне аман жетті.",
        book_title: "Алтын сақа",
        mechanic: "character_pick",
        points: 10,
        options: [
          { id: "g1-o5", text: "Алтын сақа иесі (Байдың баласы) 🏹", emoji: "🏹", is_correct: true, explanation_kk: "Жарайсың! Бұл — Алтын сақа ертегісінің батыр кейіпкері." },
          { id: "g1-o6", text: "Қаңбақ шал 👴", emoji: "👴", is_correct: false },
          { id: "g1-o7", text: "Алдар көсе 🎭", emoji: "🎭", is_correct: false },
        ],
      },
      {
        id: "g1-q3",
        game_id: "game-1",
        question_text: "Алып Дәуді ақылымен, құртты тас деп қысып қорқытқан кейіпкер кім?",
        clue_kk: "Ол өзі жеңіл болса да, ақылы өте өткір еді.",
        book_title: "Қаңбақ шал",
        mechanic: "character_pick",
        points: 10,
        options: [
          { id: "g1-o8", text: "Қаңбақ шал 👴", emoji: "👴", is_correct: true, explanation_kk: "Өте жақсы! Қаңбақ шал алып Дәуді күшпен емес, ақылмен жеңді." },
          { id: "g1-o9", text: "Шығайбай 💰", emoji: "💰", is_correct: false },
          { id: "g1-o10", text: "Мысық 🐱", emoji: "🐱", is_correct: false },
        ],
      },
    ],
  },

  // 2. Оқиғаны ретімен орналастыр
  {
    id: "game-2",
    key: "order_events",
    title: "Оқиғаны ретімен орналастыр",
    subtitle: "Оқиғалар тізбегін 1-ден 4-ке дейін дұрыс ретте",
    category: "Логика & Тізбек",
    description: "Мәтіндегі оқиғалардың басы, ортасы мен соңын шатастырмай, дұрыс ретпен қой!",
    book_id: "book-1",
    book_title: "Мақта қыз бен мысық",
    emoji: "🧩",
    color: "purple",
    bg_gradient: "from-purple-500 to-indigo-600",
    points_reward: 30,
    coins_reward: 40,
    badge_reward: "Логика шебері 🧩",
    questions_count: 2,
    difficulty: "орташа",
    questions: [
      {
        id: "g2-q1",
        game_id: "game-2",
        question_text: "«Мақта қыз бен мысық» ертегісіндегі оқиғаларды дұрыс ретпен тіз:",
        book_title: "Мақта қыз бен мысық",
        mechanic: "drag_order",
        points: 15,
        options: [],
        order_sequence: [
          { id: "seq-1", text: "1. Мақта қыз мейіз тауып, мысығын шақырды", correctPos: 1 },
          { id: "seq-2", text: "2. Мысық қатықты төгіп, Мақта қыз оның құйрығын кесіп алды", correctPos: 2 },
          { id: "seq-3", text: "3. Мысық сиырға, ағашқа және қызға барып көмек сұрады", correctPos: 3 },
          { id: "seq-4", text: "4. Мысық қатықты әкеліп, Мақта қызбен қайта достасты", correctPos: 4 },
        ],
      },
      {
        id: "g2-q2",
        game_id: "game-2",
        question_text: "«Әке мен бала» әңгімесінің реттілігін құрастыр:",
        book_title: "Әке мен бала",
        mechanic: "drag_order",
        points: 15,
        options: [],
        order_sequence: [
          { id: "seq-5", text: "1. Әкесі баласына ескі тағаны көтеруді айтты", correctPos: 1 },
          { id: "seq-6", text: "2. Бала ерініп тағаны алмады, әкесі өзі көтеріп алды", correctPos: 2 },
          { id: "seq-7", text: "3. Әкесі тағаны сатып, қызыл шие сатып алды", correctPos: 3 },
          { id: "seq-8", text: "4. Бала әр шиені алу үшін жерге он рет иілді", correctPos: 4 },
        ],
      },
    ],
  },

  // 3. Жақсы әрекетті тап
  {
    id: "game-3",
    key: "find_good_action",
    title: "Жақсы әрекетті тап",
    subtitle: "Өнегелі және мейірімді әрекетті таңда",
    category: "Өнеге & Ізгілік",
    description: "Берілген өмірлік жағдаяттардан ең ізгі, адамгершілікке толы дұрыс әрекетті тап!",
    book_id: "book-4",
    book_title: "Тәрбиелік әңгімелер",
    emoji: "🔍",
    color: "green",
    bg_gradient: "from-emerald-500 to-teal-600",
    points_reward: 30,
    coins_reward: 40,
    badge_reward: "Мейірімді жүрек ❤️",
    questions_count: 3,
    difficulty: "жеңіл",
    questions: [
      {
        id: "g3-q1",
        game_id: "game-3",
        question_text: "Сыныптасың сабақта қарындашын ұмытып кетіп, қиналса не істейсің?",
        book_title: "Достық өнегесі",
        mechanic: "action_pick",
        points: 10,
        options: [
          { id: "g3-o1", text: "Артық қарындашымды ұсынып, көмектесемін ✏️", emoji: "✏️", is_correct: true, explanation_kk: "Жарайсың! Досқа көмектесу — нағыз жомарттық!" },
          { id: "g3-o2", text: "Көрмегендей болып, үндемей отырамын", emoji: "🙈", is_correct: false },
          { id: "g3-o3", text: "Оған күліп, мұғалімге айтамын", emoji: "❌", is_correct: false },
        ],
      },
      {
        id: "g3-q2",
        game_id: "game-3",
        question_text: "Аулада үсіп, тоңып жүрген кішкентай құсты көрсең не істейсің?",
        book_title: "Қамқорлық",
        mechanic: "action_pick",
        points: 10,
        options: [
          { id: "g3-o4", text: "Ағашқа жемсалғыш жасап, жем мен жылы су қоямын 🐦", emoji: "🐦", is_correct: true, explanation_kk: "Керемет! Жануарларға қамқорлық жүректі мейірімге толтырады." },
          { id: "g3-o5", text: "Тас лақтырып үркітемін", emoji: "🚫", is_correct: false },
          { id: "g3-o6", text: "Қарап тұрып өтіп кетемін", emoji: "🚶", is_correct: false },
        ],
      },
      {
        id: "g3-q3",
        game_id: "game-3",
        question_text: "Үйде анаң көп жұмыстан шаршап отырса не істейсің?",
        book_title: "Еңбекқорлық",
        mechanic: "action_pick",
        points: 10,
        options: [
          { id: "g3-o7", text: "Бөлмемді өзім жинап, ыстық шай құйып беремін ☕", emoji: "☕", is_correct: true, explanation_kk: "Өте жақсы! Ата-анаға қолғабыс ету — үлкен сауап!" },
          { id: "g3-o8", text: "Телефон ойнап, мазасын аламын", emoji: "📱", is_correct: false },
          { id: "g3-o9", text: "Ойыншықтарымды шашып тастаймын", emoji: "🧸", is_correct: false },
        ],
      },
    ],
  },

  // 4. Мен кейіпкер болсам...
  {
    id: "game-4",
    key: "if_i_were_hero",
    title: "Мен кейіпкер болсам...",
    subtitle: "Кейіпкер орнына өзіңді қойып, шешім қабылда",
    category: "Шешім қабылдау",
    description: "Ертегідегі кейіпкердің қиын сәтінде сен болсаң қандай ақылды әрі адал қадам жасар едің?",
    book_id: "book-2",
    book_title: "Алтын сақа",
    emoji: "🎭",
    color: "amber",
    bg_gradient: "from-amber-400 to-orange-500",
    points_reward: 30,
    coins_reward: 40,
    badge_reward: "Ақылды дана 🎭",
    questions_count: 2,
    difficulty: "орташа",
    questions: [
      {
        id: "g4-q1",
        game_id: "game-4",
        question_text: "Егер сен Мақта қыздың орнында болсаң, мысық келмегенде не істер едің?",
        book_title: "Мақта қыз",
        mechanic: "scenario_choice",
        points: 15,
        options: [
          { id: "g4-o1", text: "Мейізді сақтап қойып, мысық келгенде бөлісіп жейтін едім 🍇", emoji: "🍇", is_correct: true, explanation_kk: "Дана шешім! Достықта шыдамдылық пен бөлісу өте маңызды." },
          { id: "g4-o2", text: "Жалғыз өзім жеп қойып, оны ренжітер едім", emoji: "😋", is_correct: false },
          { id: "g4-o3", text: "Мысықты үйден қуып жіберер едім", emoji: "🚪", is_correct: false },
        ],
      },
      {
        id: "g4-q2",
        game_id: "game-4",
        question_text: "Егер сен «Әке мен бала» ертегісіндегі бала болсаң, әкең тағаны ал дегенде не істер едің?",
        book_title: "Әке мен бала",
        mechanic: "scenario_choice",
        points: 15,
        options: [
          { id: "g4-o4", text: "Ерінбей бірден көтеріп алып, әкеме берер едім 🌾", emoji: "🌾", is_correct: true, explanation_kk: "Жарайсың! Үлкеннің сөзін тыңдап, еңбектен қашпау — ең ізгі қасиет." },
          { id: "g4-o5", text: "Жолда тастап кетер едім", emoji: "🚶", is_correct: false },
        ],
      },
    ],
  },

  // 5. Дұрыс па, бұрыс па?
  {
    id: "game-5",
    key: "true_false_speed",
    title: "Дұрыс па, бұрыс па?",
    subtitle: "Шындық пен қатені жылдам анықта",
    category: "Жылдамдық & Сауаттылық",
    description: "Оқыған мәтіндерің бойынша пікірлерді оқып, жылдам «Дұрыс» немесе «Бұрыс» деп жауап бер!",
    book_id: "book-1",
    book_title: "Қазақ ертегілері",
    emoji: "✅",
    color: "coral",
    bg_gradient: "from-rose-500 to-red-600",
    points_reward: 30,
    coins_reward: 40,
    badge_reward: "Жүйрік оқырман ⚡",
    questions_count: 3,
    difficulty: "жеңіл",
    questions: [
      {
        id: "g5-q1",
        game_id: "game-5",
        question_text: "Мақта қыз мысық барлық тапсырманы орындап қатықты әкелген соң, оның құйрығын қайтарып берді.",
        book_title: "Мақта қыз бен мысық",
        mechanic: "true_false",
        points: 10,
        options: [
          { id: "g5-o1", text: "Дұрыс (Шындық) 👍", emoji: "👍", is_correct: true, explanation_kk: "Дұрыс! Мақта қыз берген уәдесінде тұрып, құйрығын қайтарды." },
          { id: "g5-o2", text: "Бұрыс (Жалған) 👎", emoji: "👎", is_correct: false },
        ],
      },
      {
        id: "g5-q2",
        game_id: "game-5",
        question_text: "Қаңбақ шал алып Дәумен төбелесіп, оны зор күшімен ұрып жықты.",
        book_title: "Қаңбақ шал",
        mechanic: "true_false",
        points: 10,
        options: [
          { id: "g5-o3", text: "Дұрыс (Шындық) 👍", emoji: "👍", is_correct: false },
          { id: "g5-o4", text: "Бұрыс (Жалған) 👎", emoji: "👎", is_correct: true, explanation_kk: "Дұрыс таптың! Қаңбақ шал Дәуді күшпен емес, өткір ақылымен жеңген болатын." },
        ],
      },
      {
        id: "g5-q3",
        game_id: "game-5",
        question_text: "Ыбырай Алтынсариннің «Әке мен бала» әңгімесі адамдарды еңбекқор болуға тәрбиелейді.",
        book_title: "Әке мен бала",
        mechanic: "true_false",
        points: 10,
        options: [
          { id: "g5-o5", text: "Дұрыс (Шындық) 👍", emoji: "👍", is_correct: true, explanation_kk: "Иә! Бұл шығарма еңбектің қадірін үйретеді." },
          { id: "g5-o6", text: "Бұрыс (Жалған) 👎", emoji: "👎", is_correct: false },
        ],
      },
    ],
  },

  // 6. Сиқырлы сандық
  {
    id: "game-6",
    key: "magic_chest",
    title: "Сиқырлы сандық",
    subtitle: "Алтын кілтті таңдап, құпия сыйлықты аш",
    category: "Сюрприз & Марапат",
    description: "Кітап оқып жинаған біліміңмен 3 сиқырлы кілттің бірін таңдап, сандықтан тосын сый мен монета ал!",
    book_id: "book-1",
    book_title: "Барлық ертегілер",
    emoji: "🎁",
    color: "yellow",
    bg_gradient: "from-amber-400 via-yellow-400 to-amber-500",
    points_reward: 50,
    coins_reward: 50,
    badge_reward: "Алтын сандық иесі 👑",
    questions_count: 1,
    difficulty: "жеңіл",
    questions: [
      {
        id: "g6-q1",
        game_id: "game-6",
        question_text: "Сиқырлы сандықтың 3 алтын кілтінің бірін таңдаңыз:",
        mechanic: "chest_unlock",
        points: 20,
        options: [],
        chest_rewards: [
          {
            keyId: 1,
            title: "Алтын жұлдыз сандығы 🌟",
            rewardKk: "+30 🪙 Монета және «Білімпаз бала» маскот стикері!",
            coins: 30,
            xp: 20,
            sticker: "🌟 🦁",
          },
          {
            keyId: 2,
            title: "Ертегілер қазынасы 📖",
            rewardKk: "+50 🪙 Монета және «Оқырман жүрегі» белгісі!",
            coins: 50,
            xp: 30,
            sticker: "💖 🌸",
          },
          {
            keyId: 3,
            title: "Жақсылық сыйы 🎁",
            rewardKk: "+40 🪙 Монета және «Батыр бала» стикері!",
            coins: 40,
            xp: 25,
            sticker: "👑 🚀",
          },
        ],
      },
    ],
  },
];
